name: ui_core
description: "A new Flutter package project."
version: 0.0.1
environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter

  go_router: ^15.0.0
  shared_preferences: ^2.3.5
  equatable: ^2.0.7
  dartz: ^0.10.1
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  loader_overlay: ^5.0.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  geolocator: ^14.0.0
  responsive_sizer: ^3.3.1
  hive: ^2.2.3
  animations: ^2.0.11